// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filemanagement.proto

package edu.kit.palladio.proto.filemanagment;

/**
 * Protobuf type {@code filemanagement.FileTreeRequest}
 */
public final class FileTreeRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:filemanagement.FileTreeRequest)
    FileTreeRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FileTreeRequest.newBuilder() to construct.
  private FileTreeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FileTreeRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FileTreeRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FileTreeRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            edu.kit.palladio.proto.filemanagment.File.Builder subBuilder = null;
            if (startingDir_ != null) {
              subBuilder = startingDir_.toBuilder();
            }
            startingDir_ = input.readMessage(edu.kit.palladio.proto.filemanagment.File.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(startingDir_);
              startingDir_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return edu.kit.palladio.proto.filemanagment.FileManagementProtos.internal_static_filemanagement_FileTreeRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return edu.kit.palladio.proto.filemanagment.FileManagementProtos.internal_static_filemanagement_FileTreeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            edu.kit.palladio.proto.filemanagment.FileTreeRequest.class, edu.kit.palladio.proto.filemanagment.FileTreeRequest.Builder.class);
  }

  public static final int STARTINGDIR_FIELD_NUMBER = 1;
  private edu.kit.palladio.proto.filemanagment.File startingDir_;
  /**
   * <code>.filemanagement.File startingDir = 1;</code>
   * @return Whether the startingDir field is set.
   */
  @java.lang.Override
  public boolean hasStartingDir() {
    return startingDir_ != null;
  }
  /**
   * <code>.filemanagement.File startingDir = 1;</code>
   * @return The startingDir.
   */
  @java.lang.Override
  public edu.kit.palladio.proto.filemanagment.File getStartingDir() {
    return startingDir_ == null ? edu.kit.palladio.proto.filemanagment.File.getDefaultInstance() : startingDir_;
  }
  /**
   * <code>.filemanagement.File startingDir = 1;</code>
   */
  @java.lang.Override
  public edu.kit.palladio.proto.filemanagment.FileOrBuilder getStartingDirOrBuilder() {
    return getStartingDir();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (startingDir_ != null) {
      output.writeMessage(1, getStartingDir());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (startingDir_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getStartingDir());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof edu.kit.palladio.proto.filemanagment.FileTreeRequest)) {
      return super.equals(obj);
    }
    edu.kit.palladio.proto.filemanagment.FileTreeRequest other = (edu.kit.palladio.proto.filemanagment.FileTreeRequest) obj;

    if (hasStartingDir() != other.hasStartingDir()) return false;
    if (hasStartingDir()) {
      if (!getStartingDir()
          .equals(other.getStartingDir())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStartingDir()) {
      hash = (37 * hash) + STARTINGDIR_FIELD_NUMBER;
      hash = (53 * hash) + getStartingDir().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static edu.kit.palladio.proto.filemanagment.FileTreeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.kit.palladio.proto.filemanagment.FileTreeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.kit.palladio.proto.filemanagment.FileTreeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.kit.palladio.proto.filemanagment.FileTreeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.kit.palladio.proto.filemanagment.FileTreeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.kit.palladio.proto.filemanagment.FileTreeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.kit.palladio.proto.filemanagment.FileTreeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.kit.palladio.proto.filemanagment.FileTreeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.kit.palladio.proto.filemanagment.FileTreeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static edu.kit.palladio.proto.filemanagment.FileTreeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.kit.palladio.proto.filemanagment.FileTreeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.kit.palladio.proto.filemanagment.FileTreeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(edu.kit.palladio.proto.filemanagment.FileTreeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code filemanagement.FileTreeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:filemanagement.FileTreeRequest)
      edu.kit.palladio.proto.filemanagment.FileTreeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.kit.palladio.proto.filemanagment.FileManagementProtos.internal_static_filemanagement_FileTreeRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.kit.palladio.proto.filemanagment.FileManagementProtos.internal_static_filemanagement_FileTreeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.kit.palladio.proto.filemanagment.FileTreeRequest.class, edu.kit.palladio.proto.filemanagment.FileTreeRequest.Builder.class);
    }

    // Construct using edu.kit.palladio.proto.filemanagment.FileTreeRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (startingDirBuilder_ == null) {
        startingDir_ = null;
      } else {
        startingDir_ = null;
        startingDirBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return edu.kit.palladio.proto.filemanagment.FileManagementProtos.internal_static_filemanagement_FileTreeRequest_descriptor;
    }

    @java.lang.Override
    public edu.kit.palladio.proto.filemanagment.FileTreeRequest getDefaultInstanceForType() {
      return edu.kit.palladio.proto.filemanagment.FileTreeRequest.getDefaultInstance();
    }

    @java.lang.Override
    public edu.kit.palladio.proto.filemanagment.FileTreeRequest build() {
      edu.kit.palladio.proto.filemanagment.FileTreeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public edu.kit.palladio.proto.filemanagment.FileTreeRequest buildPartial() {
      edu.kit.palladio.proto.filemanagment.FileTreeRequest result = new edu.kit.palladio.proto.filemanagment.FileTreeRequest(this);
      if (startingDirBuilder_ == null) {
        result.startingDir_ = startingDir_;
      } else {
        result.startingDir_ = startingDirBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof edu.kit.palladio.proto.filemanagment.FileTreeRequest) {
        return mergeFrom((edu.kit.palladio.proto.filemanagment.FileTreeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(edu.kit.palladio.proto.filemanagment.FileTreeRequest other) {
      if (other == edu.kit.palladio.proto.filemanagment.FileTreeRequest.getDefaultInstance()) return this;
      if (other.hasStartingDir()) {
        mergeStartingDir(other.getStartingDir());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      edu.kit.palladio.proto.filemanagment.FileTreeRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (edu.kit.palladio.proto.filemanagment.FileTreeRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private edu.kit.palladio.proto.filemanagment.File startingDir_;
    private com.google.protobuf.SingleFieldBuilderV3<
        edu.kit.palladio.proto.filemanagment.File, edu.kit.palladio.proto.filemanagment.File.Builder, edu.kit.palladio.proto.filemanagment.FileOrBuilder> startingDirBuilder_;
    /**
     * <code>.filemanagement.File startingDir = 1;</code>
     * @return Whether the startingDir field is set.
     */
    public boolean hasStartingDir() {
      return startingDirBuilder_ != null || startingDir_ != null;
    }
    /**
     * <code>.filemanagement.File startingDir = 1;</code>
     * @return The startingDir.
     */
    public edu.kit.palladio.proto.filemanagment.File getStartingDir() {
      if (startingDirBuilder_ == null) {
        return startingDir_ == null ? edu.kit.palladio.proto.filemanagment.File.getDefaultInstance() : startingDir_;
      } else {
        return startingDirBuilder_.getMessage();
      }
    }
    /**
     * <code>.filemanagement.File startingDir = 1;</code>
     */
    public Builder setStartingDir(edu.kit.palladio.proto.filemanagment.File value) {
      if (startingDirBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        startingDir_ = value;
        onChanged();
      } else {
        startingDirBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.filemanagement.File startingDir = 1;</code>
     */
    public Builder setStartingDir(
        edu.kit.palladio.proto.filemanagment.File.Builder builderForValue) {
      if (startingDirBuilder_ == null) {
        startingDir_ = builderForValue.build();
        onChanged();
      } else {
        startingDirBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.filemanagement.File startingDir = 1;</code>
     */
    public Builder mergeStartingDir(edu.kit.palladio.proto.filemanagment.File value) {
      if (startingDirBuilder_ == null) {
        if (startingDir_ != null) {
          startingDir_ =
            edu.kit.palladio.proto.filemanagment.File.newBuilder(startingDir_).mergeFrom(value).buildPartial();
        } else {
          startingDir_ = value;
        }
        onChanged();
      } else {
        startingDirBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.filemanagement.File startingDir = 1;</code>
     */
    public Builder clearStartingDir() {
      if (startingDirBuilder_ == null) {
        startingDir_ = null;
        onChanged();
      } else {
        startingDir_ = null;
        startingDirBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.filemanagement.File startingDir = 1;</code>
     */
    public edu.kit.palladio.proto.filemanagment.File.Builder getStartingDirBuilder() {
      
      onChanged();
      return getStartingDirFieldBuilder().getBuilder();
    }
    /**
     * <code>.filemanagement.File startingDir = 1;</code>
     */
    public edu.kit.palladio.proto.filemanagment.FileOrBuilder getStartingDirOrBuilder() {
      if (startingDirBuilder_ != null) {
        return startingDirBuilder_.getMessageOrBuilder();
      } else {
        return startingDir_ == null ?
            edu.kit.palladio.proto.filemanagment.File.getDefaultInstance() : startingDir_;
      }
    }
    /**
     * <code>.filemanagement.File startingDir = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        edu.kit.palladio.proto.filemanagment.File, edu.kit.palladio.proto.filemanagment.File.Builder, edu.kit.palladio.proto.filemanagment.FileOrBuilder> 
        getStartingDirFieldBuilder() {
      if (startingDirBuilder_ == null) {
        startingDirBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            edu.kit.palladio.proto.filemanagment.File, edu.kit.palladio.proto.filemanagment.File.Builder, edu.kit.palladio.proto.filemanagment.FileOrBuilder>(
                getStartingDir(),
                getParentForChildren(),
                isClean());
        startingDir_ = null;
      }
      return startingDirBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:filemanagement.FileTreeRequest)
  }

  // @@protoc_insertion_point(class_scope:filemanagement.FileTreeRequest)
  private static final edu.kit.palladio.proto.filemanagment.FileTreeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new edu.kit.palladio.proto.filemanagment.FileTreeRequest();
  }

  public static edu.kit.palladio.proto.filemanagment.FileTreeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FileTreeRequest>
      PARSER = new com.google.protobuf.AbstractParser<FileTreeRequest>() {
    @java.lang.Override
    public FileTreeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FileTreeRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FileTreeRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FileTreeRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public edu.kit.palladio.proto.filemanagment.FileTreeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

