// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filemanagement.proto

package edu.kit.palladio.proto.filemanagment;

public interface WriteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:filemanagement.WriteResponse)
    com.google.protobuf.MessageOrBuilder {
}
