// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: projectmanagement.proto

package edu.kit.palladio.proto.projectmanagement;

public interface DeleteProjectResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:projectmanagement.DeleteProjectResponse)
    com.google.protobuf.MessageOrBuilder {
}
