// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filemanagement.proto

package edu.kit.palladio.proto.filemanagement;

public interface CreateFileResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:filemanagement.CreateFileResponse)
    com.google.protobuf.MessageOrBuilder {
}
