// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filemanagement.proto

package edu.kit.palladio.proto.filemanagement;

public interface DeleteFileResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:filemanagement.DeleteFileResponse)
    com.google.protobuf.MessageOrBuilder {
}
