// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filemanagement.proto

package edu.kit.palladio.proto.filemanagement;

public interface FileTreeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:filemanagement.FileTreeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.filemanagement.File startingDir = 1;</code>
   * @return Whether the startingDir field is set.
   */
  boolean hasStartingDir();
  /**
   * <code>.filemanagement.File startingDir = 1;</code>
   * @return The startingDir.
   */
  edu.kit.palladio.proto.filemanagement.File getStartingDir();
  /**
   * <code>.filemanagement.File startingDir = 1;</code>
   */
  edu.kit.palladio.proto.filemanagement.FileOrBuilder getStartingDirOrBuilder();
}
