// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: projectmanagement.proto

package edu.kit.palladio.proto.projectmanagement;

public interface GetProjectsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:projectmanagement.GetProjectsRequest)
    com.google.protobuf.MessageOrBuilder {
}
