// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: projectmanagement.proto

package edu.kit.palladio.proto.projectmanagement;

public interface ProjectsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:projectmanagement.Projects)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .projectmanagement.Project projects = 1;</code>
   */
  java.util.List<edu.kit.palladio.proto.projectmanagement.Project> 
      getProjectsList();
  /**
   * <code>repeated .projectmanagement.Project projects = 1;</code>
   */
  edu.kit.palladio.proto.projectmanagement.Project getProjects(int index);
  /**
   * <code>repeated .projectmanagement.Project projects = 1;</code>
   */
  int getProjectsCount();
  /**
   * <code>repeated .projectmanagement.Project projects = 1;</code>
   */
  java.util.List<? extends edu.kit.palladio.proto.projectmanagement.ProjectOrBuilder> 
      getProjectsOrBuilderList();
  /**
   * <code>repeated .projectmanagement.Project projects = 1;</code>
   */
  edu.kit.palladio.proto.projectmanagement.ProjectOrBuilder getProjectsOrBuilder(
      int index);
}
