// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: projectmanagement.proto

package edu.kit.palladio.proto.projectmanagement;

public interface ProjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:projectmanagement.Project)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string projectId = 1;</code>
   * @return The projectId.
   */
  java.lang.String getProjectId();
  /**
   * <code>string projectId = 1;</code>
   * @return The bytes for projectId.
   */
  com.google.protobuf.ByteString
      getProjectIdBytes();
}
