// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: projectmanagement.proto

package edu.kit.palladio.proto.projectmanagement;

public final class ProjectManagementProtos {
  private ProjectManagementProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_projectmanagement_Project_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_projectmanagement_Project_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_projectmanagement_Projects_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_projectmanagement_Projects_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_projectmanagement_CreateProjectResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_projectmanagement_CreateProjectResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_projectmanagement_DeleteProjectResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_projectmanagement_DeleteProjectResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_projectmanagement_GetProjectRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_projectmanagement_GetProjectRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027projectmanagement.proto\022\021projectmanage" +
      "ment\"\034\n\007Project\022\021\n\tprojectId\030\001 \001(\t\"8\n\010Pr" +
      "ojects\022,\n\010projects\030\001 \003(\0132\032.projectmanage" +
      "ment.Project\"\027\n\025CreateProjectResponse\"\027\n" +
      "\025DeleteProjectResponse\"\023\n\021GetProjectRequ" +
      "est2\336\002\n\016ProjectManager\022W\n\rcreateProject\022" +
      "\032.projectmanagement.Project\032(.projectman" +
      "agement.CreateProjectResponse\"\000\022W\n\rdelet" +
      "eProject\022\032.projectmanagement.Project\032(.p" +
      "rojectmanagement.DeleteProjectResponse\"\000" +
      "\022F\n\ngetProject\022\032.projectmanagement.Proje" +
      "ct\032\032.projectmanagement.Project\"\000\022R\n\013getP" +
      "rojects\022$.projectmanagement.GetProjectRe" +
      "quest\032\033.projectmanagement.Projects\"\000BE\n(" +
      "edu.kit.palladio.proto.projectmanagement" +
      "B\027ProjectManagementProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_projectmanagement_Project_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_projectmanagement_Project_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_projectmanagement_Project_descriptor,
        new java.lang.String[] { "ProjectId", });
    internal_static_projectmanagement_Projects_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_projectmanagement_Projects_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_projectmanagement_Projects_descriptor,
        new java.lang.String[] { "Projects", });
    internal_static_projectmanagement_CreateProjectResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_projectmanagement_CreateProjectResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_projectmanagement_CreateProjectResponse_descriptor,
        new java.lang.String[] { });
    internal_static_projectmanagement_DeleteProjectResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_projectmanagement_DeleteProjectResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_projectmanagement_DeleteProjectResponse_descriptor,
        new java.lang.String[] { });
    internal_static_projectmanagement_GetProjectRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_projectmanagement_GetProjectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_projectmanagement_GetProjectRequest_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
