// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: projectmanagement.proto

package edu.kit.palladio.proto.projectmanagement;

/**
 * Protobuf type {@code projectmanagement.Projects}
 */
public final class Projects extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:projectmanagement.Projects)
    ProjectsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Projects.newBuilder() to construct.
  private Projects(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Projects() {
    projects_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Projects();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Projects(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              projects_ = new java.util.ArrayList<edu.kit.palladio.proto.projectmanagement.Project>();
              mutable_bitField0_ |= 0x00000001;
            }
            projects_.add(
                input.readMessage(edu.kit.palladio.proto.projectmanagement.Project.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        projects_ = java.util.Collections.unmodifiableList(projects_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return edu.kit.palladio.proto.projectmanagement.ProjectManagementProtos.internal_static_projectmanagement_Projects_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return edu.kit.palladio.proto.projectmanagement.ProjectManagementProtos.internal_static_projectmanagement_Projects_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            edu.kit.palladio.proto.projectmanagement.Projects.class, edu.kit.palladio.proto.projectmanagement.Projects.Builder.class);
  }

  public static final int PROJECTS_FIELD_NUMBER = 1;
  private java.util.List<edu.kit.palladio.proto.projectmanagement.Project> projects_;
  /**
   * <code>repeated .projectmanagement.Project projects = 1;</code>
   */
  @java.lang.Override
  public java.util.List<edu.kit.palladio.proto.projectmanagement.Project> getProjectsList() {
    return projects_;
  }
  /**
   * <code>repeated .projectmanagement.Project projects = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends edu.kit.palladio.proto.projectmanagement.ProjectOrBuilder> 
      getProjectsOrBuilderList() {
    return projects_;
  }
  /**
   * <code>repeated .projectmanagement.Project projects = 1;</code>
   */
  @java.lang.Override
  public int getProjectsCount() {
    return projects_.size();
  }
  /**
   * <code>repeated .projectmanagement.Project projects = 1;</code>
   */
  @java.lang.Override
  public edu.kit.palladio.proto.projectmanagement.Project getProjects(int index) {
    return projects_.get(index);
  }
  /**
   * <code>repeated .projectmanagement.Project projects = 1;</code>
   */
  @java.lang.Override
  public edu.kit.palladio.proto.projectmanagement.ProjectOrBuilder getProjectsOrBuilder(
      int index) {
    return projects_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < projects_.size(); i++) {
      output.writeMessage(1, projects_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < projects_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, projects_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof edu.kit.palladio.proto.projectmanagement.Projects)) {
      return super.equals(obj);
    }
    edu.kit.palladio.proto.projectmanagement.Projects other = (edu.kit.palladio.proto.projectmanagement.Projects) obj;

    if (!getProjectsList()
        .equals(other.getProjectsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getProjectsCount() > 0) {
      hash = (37 * hash) + PROJECTS_FIELD_NUMBER;
      hash = (53 * hash) + getProjectsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static edu.kit.palladio.proto.projectmanagement.Projects parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.kit.palladio.proto.projectmanagement.Projects parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.kit.palladio.proto.projectmanagement.Projects parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.kit.palladio.proto.projectmanagement.Projects parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.kit.palladio.proto.projectmanagement.Projects parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.kit.palladio.proto.projectmanagement.Projects parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.kit.palladio.proto.projectmanagement.Projects parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.kit.palladio.proto.projectmanagement.Projects parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.kit.palladio.proto.projectmanagement.Projects parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static edu.kit.palladio.proto.projectmanagement.Projects parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.kit.palladio.proto.projectmanagement.Projects parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.kit.palladio.proto.projectmanagement.Projects parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(edu.kit.palladio.proto.projectmanagement.Projects prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code projectmanagement.Projects}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:projectmanagement.Projects)
      edu.kit.palladio.proto.projectmanagement.ProjectsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.kit.palladio.proto.projectmanagement.ProjectManagementProtos.internal_static_projectmanagement_Projects_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.kit.palladio.proto.projectmanagement.ProjectManagementProtos.internal_static_projectmanagement_Projects_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.kit.palladio.proto.projectmanagement.Projects.class, edu.kit.palladio.proto.projectmanagement.Projects.Builder.class);
    }

    // Construct using edu.kit.palladio.proto.projectmanagement.Projects.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getProjectsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (projectsBuilder_ == null) {
        projects_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        projectsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return edu.kit.palladio.proto.projectmanagement.ProjectManagementProtos.internal_static_projectmanagement_Projects_descriptor;
    }

    @java.lang.Override
    public edu.kit.palladio.proto.projectmanagement.Projects getDefaultInstanceForType() {
      return edu.kit.palladio.proto.projectmanagement.Projects.getDefaultInstance();
    }

    @java.lang.Override
    public edu.kit.palladio.proto.projectmanagement.Projects build() {
      edu.kit.palladio.proto.projectmanagement.Projects result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public edu.kit.palladio.proto.projectmanagement.Projects buildPartial() {
      edu.kit.palladio.proto.projectmanagement.Projects result = new edu.kit.palladio.proto.projectmanagement.Projects(this);
      int from_bitField0_ = bitField0_;
      if (projectsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          projects_ = java.util.Collections.unmodifiableList(projects_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.projects_ = projects_;
      } else {
        result.projects_ = projectsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof edu.kit.palladio.proto.projectmanagement.Projects) {
        return mergeFrom((edu.kit.palladio.proto.projectmanagement.Projects)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(edu.kit.palladio.proto.projectmanagement.Projects other) {
      if (other == edu.kit.palladio.proto.projectmanagement.Projects.getDefaultInstance()) return this;
      if (projectsBuilder_ == null) {
        if (!other.projects_.isEmpty()) {
          if (projects_.isEmpty()) {
            projects_ = other.projects_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureProjectsIsMutable();
            projects_.addAll(other.projects_);
          }
          onChanged();
        }
      } else {
        if (!other.projects_.isEmpty()) {
          if (projectsBuilder_.isEmpty()) {
            projectsBuilder_.dispose();
            projectsBuilder_ = null;
            projects_ = other.projects_;
            bitField0_ = (bitField0_ & ~0x00000001);
            projectsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getProjectsFieldBuilder() : null;
          } else {
            projectsBuilder_.addAllMessages(other.projects_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      edu.kit.palladio.proto.projectmanagement.Projects parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (edu.kit.palladio.proto.projectmanagement.Projects) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<edu.kit.palladio.proto.projectmanagement.Project> projects_ =
      java.util.Collections.emptyList();
    private void ensureProjectsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        projects_ = new java.util.ArrayList<edu.kit.palladio.proto.projectmanagement.Project>(projects_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.kit.palladio.proto.projectmanagement.Project, edu.kit.palladio.proto.projectmanagement.Project.Builder, edu.kit.palladio.proto.projectmanagement.ProjectOrBuilder> projectsBuilder_;

    /**
     * <code>repeated .projectmanagement.Project projects = 1;</code>
     */
    public java.util.List<edu.kit.palladio.proto.projectmanagement.Project> getProjectsList() {
      if (projectsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(projects_);
      } else {
        return projectsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .projectmanagement.Project projects = 1;</code>
     */
    public int getProjectsCount() {
      if (projectsBuilder_ == null) {
        return projects_.size();
      } else {
        return projectsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .projectmanagement.Project projects = 1;</code>
     */
    public edu.kit.palladio.proto.projectmanagement.Project getProjects(int index) {
      if (projectsBuilder_ == null) {
        return projects_.get(index);
      } else {
        return projectsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .projectmanagement.Project projects = 1;</code>
     */
    public Builder setProjects(
        int index, edu.kit.palladio.proto.projectmanagement.Project value) {
      if (projectsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProjectsIsMutable();
        projects_.set(index, value);
        onChanged();
      } else {
        projectsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .projectmanagement.Project projects = 1;</code>
     */
    public Builder setProjects(
        int index, edu.kit.palladio.proto.projectmanagement.Project.Builder builderForValue) {
      if (projectsBuilder_ == null) {
        ensureProjectsIsMutable();
        projects_.set(index, builderForValue.build());
        onChanged();
      } else {
        projectsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .projectmanagement.Project projects = 1;</code>
     */
    public Builder addProjects(edu.kit.palladio.proto.projectmanagement.Project value) {
      if (projectsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProjectsIsMutable();
        projects_.add(value);
        onChanged();
      } else {
        projectsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .projectmanagement.Project projects = 1;</code>
     */
    public Builder addProjects(
        int index, edu.kit.palladio.proto.projectmanagement.Project value) {
      if (projectsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProjectsIsMutable();
        projects_.add(index, value);
        onChanged();
      } else {
        projectsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .projectmanagement.Project projects = 1;</code>
     */
    public Builder addProjects(
        edu.kit.palladio.proto.projectmanagement.Project.Builder builderForValue) {
      if (projectsBuilder_ == null) {
        ensureProjectsIsMutable();
        projects_.add(builderForValue.build());
        onChanged();
      } else {
        projectsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .projectmanagement.Project projects = 1;</code>
     */
    public Builder addProjects(
        int index, edu.kit.palladio.proto.projectmanagement.Project.Builder builderForValue) {
      if (projectsBuilder_ == null) {
        ensureProjectsIsMutable();
        projects_.add(index, builderForValue.build());
        onChanged();
      } else {
        projectsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .projectmanagement.Project projects = 1;</code>
     */
    public Builder addAllProjects(
        java.lang.Iterable<? extends edu.kit.palladio.proto.projectmanagement.Project> values) {
      if (projectsBuilder_ == null) {
        ensureProjectsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, projects_);
        onChanged();
      } else {
        projectsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .projectmanagement.Project projects = 1;</code>
     */
    public Builder clearProjects() {
      if (projectsBuilder_ == null) {
        projects_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        projectsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .projectmanagement.Project projects = 1;</code>
     */
    public Builder removeProjects(int index) {
      if (projectsBuilder_ == null) {
        ensureProjectsIsMutable();
        projects_.remove(index);
        onChanged();
      } else {
        projectsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .projectmanagement.Project projects = 1;</code>
     */
    public edu.kit.palladio.proto.projectmanagement.Project.Builder getProjectsBuilder(
        int index) {
      return getProjectsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .projectmanagement.Project projects = 1;</code>
     */
    public edu.kit.palladio.proto.projectmanagement.ProjectOrBuilder getProjectsOrBuilder(
        int index) {
      if (projectsBuilder_ == null) {
        return projects_.get(index);  } else {
        return projectsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .projectmanagement.Project projects = 1;</code>
     */
    public java.util.List<? extends edu.kit.palladio.proto.projectmanagement.ProjectOrBuilder> 
         getProjectsOrBuilderList() {
      if (projectsBuilder_ != null) {
        return projectsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(projects_);
      }
    }
    /**
     * <code>repeated .projectmanagement.Project projects = 1;</code>
     */
    public edu.kit.palladio.proto.projectmanagement.Project.Builder addProjectsBuilder() {
      return getProjectsFieldBuilder().addBuilder(
          edu.kit.palladio.proto.projectmanagement.Project.getDefaultInstance());
    }
    /**
     * <code>repeated .projectmanagement.Project projects = 1;</code>
     */
    public edu.kit.palladio.proto.projectmanagement.Project.Builder addProjectsBuilder(
        int index) {
      return getProjectsFieldBuilder().addBuilder(
          index, edu.kit.palladio.proto.projectmanagement.Project.getDefaultInstance());
    }
    /**
     * <code>repeated .projectmanagement.Project projects = 1;</code>
     */
    public java.util.List<edu.kit.palladio.proto.projectmanagement.Project.Builder> 
         getProjectsBuilderList() {
      return getProjectsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.kit.palladio.proto.projectmanagement.Project, edu.kit.palladio.proto.projectmanagement.Project.Builder, edu.kit.palladio.proto.projectmanagement.ProjectOrBuilder> 
        getProjectsFieldBuilder() {
      if (projectsBuilder_ == null) {
        projectsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            edu.kit.palladio.proto.projectmanagement.Project, edu.kit.palladio.proto.projectmanagement.Project.Builder, edu.kit.palladio.proto.projectmanagement.ProjectOrBuilder>(
                projects_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        projects_ = null;
      }
      return projectsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:projectmanagement.Projects)
  }

  // @@protoc_insertion_point(class_scope:projectmanagement.Projects)
  private static final edu.kit.palladio.proto.projectmanagement.Projects DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new edu.kit.palladio.proto.projectmanagement.Projects();
  }

  public static edu.kit.palladio.proto.projectmanagement.Projects getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Projects>
      PARSER = new com.google.protobuf.AbstractParser<Projects>() {
    @java.lang.Override
    public Projects parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Projects(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Projects> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Projects> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public edu.kit.palladio.proto.projectmanagement.Projects getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

